COMBOS = [
    {
        "type": "RGB",
        "feature": "ABXY lights on/off",
        "combo": "Hold LB + RB for 6 seconds",
        "notes": "Toggles face-button lights.",
    },
    {
        "type": "RGB",
        "feature": "Joystick lights on/off",
        "combo": "Hold LT + RT for 6 seconds",
        "notes": "Toggles stick RGB lights.",
    },
    {
        "type": "RGB",
        "feature": "Side lights on/off",
        "combo": "Hold LB + RT for 6 seconds",
        "notes": "Transparent model only.",
    },
    {
        "type": "RGB",
        "feature": "Brightness up",
        "combo": "Hold Back + D-pad Up",
        "notes": "Increases LED brightness.",
    },
    {
        "type": "RGB",
        "feature": "Brightness down",
        "combo": "Hold Back + D-pad Down",
        "notes": "Decreases LED brightness.",
    },
    {
        "type": "RGB",
        "feature": "Change RGB mode",
        "combo": "Hold Select + D-pad Left",
        "notes": "Cycles mixed wave, breathing, single color.",
    },
    {
        "type": "RGB",
        "feature": "Next single color",
        "combo": "Hold Select + D-pad Right",
        "notes": "Works inside single color mode.",
    },
    {
        "type": "RGB",
        "feature": "Joystick operation RGB mode",
        "combo": "Hold Back + D-pad Left",
        "notes": "Joystick lights react to stick movement.",
    },
    {
        "type": "Vibration",
        "feature": "Increase vibration level",
        "combo": "Hold Turbo + Left Stick Up",
        "notes": "Levels: 0%, 30%, 70%, 100%.",
    },
    {
        "type": "Vibration",
        "feature": "Decrease vibration level",
        "combo": "Hold Turbo + Left Stick Down",
        "notes": "Levels: 0%, 30%, 70%, 100%.",
    },
    {
        "type": "Turbo",
        "feature": "Manual/auto turbo/off for one button",
        "combo": "Hold target button, press Turbo",
        "notes": "Target: A/B/X/Y/LB/LT/RB/RT. Repeat to cycle.",
    },
    {
        "type": "Turbo",
        "feature": "Clear all turbo",
        "combo": "Hold Turbo for 6 seconds",
        "notes": "Controller vibrates when cleared.",
    },
    {
        "type": "Turbo",
        "feature": "Turbo speed up/down",
        "combo": "Hold Turbo + Right Stick Up/Down",
        "notes": "Slow 5/s, medium 15/s, fast 25/s.",
    },
    {
        "type": "Macro",
        "feature": "Set ML or MR macro",
        "combo": "Hold Turbo + ML/MR for 2 seconds",
        "notes": "Press sequence, then press ML/MR once to save.",
    },
    {
        "type": "Macro",
        "feature": "Clear ML or MR macro",
        "combo": "Hold Turbo + ML/MR for 2 seconds, then press same ML/MR",
        "notes": "Clears the current macro slot.",
    },
    {
        "type": "Mapping",
        "feature": "Swap D-pad and left stick",
        "combo": "Double press Vib/Capture",
        "notes": "Useful if D-pad and stick behavior feels wrong.",
    },
    {
        "type": "Battery",
        "feature": "Check battery level",
        "combo": "Press Turbo + Back once",
        "notes": "Controller LEDs show battery level.",
    },
    {
        "type": "Reset",
        "feature": "Factory settings reset",
        "combo": "Hold Turbo + Back for 6 seconds",
        "notes": "Resets ML/MR, vibration level, turbo speed.",
    },
    {
        "type": "Reset",
        "feature": "Hardware reset",
        "combo": "Hold Home for 10 seconds",
        "notes": "Use only if the controller is stuck.",
    },
    {
        "type": "Calibration",
        "feature": "Joystick/trigger calibration",
        "combo": "Short trigger locks, then Turbo + Home + Select",
        "notes": "Rotate sticks, press LT/RT slowly, press Select to exit.",
    },
]
